spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://booking-service:8081
          predicates:
            - Path=/api/bookings/**
          filters:
            - AuthenticationFilter
        - id: room-service
          uri: http://room-service:8082
          predicates:
            - Path=/api/rooms/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://api-gateway
          predicates:
            - Path=/api/auth/**
